/* 🤖 this file was generated by svg-to-ts */
export const wgIconsCloudBlack: {
  name: 'cloud_black';
  data: string;
} = {
  name: 'cloud_black',
  data: `<svg width="48" height="48" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M24 25.1716L32.4852 33.6568L29.6568 36.4852L26 32.83V44H22V32.826L18.3431 36.4852L15.5147 33.6568L24 25.1716ZM24 4C31.1868 4 37.1088 9.41522 37.9082 16.3879C42.5716 17.6631 46 21.9312 46 27C46 32.7376 41.6072 37.4492 36.0012 37.9552L36.0018 33.9288C39.3932 33.4428 42 30.5258 42 27C42 23.134 38.866 20 35 20C34.5824 20 34.1734 20.0366 33.7774 20.108C33.9232 19.4284 34 18.7232 34 18C34 12.4772 29.5228 8 24 8C18.4772 8 14 12.4772 14 18C14 18.7232 14.0768 19.4284 14.2241 20.1066C13.8266 20.0366 13.4176 20 13 20C9.134 20 6 23.134 6 27C6 30.4006 8.42482 33.2348 11.6397 33.868L12.0001 33.9292L12.0008 37.9552C6.39392 37.4504 2 32.7384 2 27C2 21.9312 5.42848 17.6631 10.093 16.3882C10.8912 9.41522 16.8132 4 24 4Z" fill="url(#paint0_linear_13_337)"/><defs><linearGradient id="paint0_linear_13_337" x1="24" y1="4" x2="24" y2="44" gradientUnits="userSpaceOnUse"><stop/><stop offset="1" stop-color="#666666" stop-opacity="0.86"/></linearGradient></defs></svg>`
};
export const wgIconsCloudLoad: {
  name: 'cloud_load';
  data: string;
} = {
  name: 'cloud_load',
  data: `<svg width="44" height="41" viewBox="0 0 44 41" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M22 21.6716L30.4852 30.1568L27.6568 32.9852L24 29.33V40.5H20V29.326L16.3431 32.9852L13.5147 30.1568L22 21.6716ZM22 0.5C29.1868 0.5 35.1088 5.91522 35.9082 12.8879C40.5716 14.1631 44 18.4312 44 23.5C44 29.2376 39.6072 33.9492 34.0012 34.4552L34.0018 30.4288C37.3932 29.9428 40 27.0258 40 23.5C40 19.634 36.866 16.5 33 16.5C32.5824 16.5 32.1734 16.5366 31.7774 16.608C31.9232 15.9284 32 15.2232 32 14.5C32 8.97716 27.5228 4.5 22 4.5C16.4772 4.5 12 8.97716 12 14.5C12 15.2232 12.0768 15.9284 12.2241 16.6066C11.8266 16.5366 11.4176 16.5 11 16.5C7.134 16.5 4 19.634 4 23.5C4 26.9006 6.42482 29.7348 9.63972 30.368L10.0001 30.4292L10.0008 34.4552C4.39392 33.9504 0 29.2384 0 23.5C0 18.4312 3.42848 14.1631 8.09296 12.8882C8.89122 5.91522 14.8132 0.5 22 0.5Z" fill="url(#paint0_linear_13_169)"/><defs><linearGradient id="paint0_linear_13_169" x1="22" y1="0.5" x2="22" y2="40.5" gradientUnits="userSpaceOnUse"><stop stop-color="#FF6510"/><stop offset="1" stop-color="#FF6510" stop-opacity="0.86"/></linearGradient></defs></svg>`
};
export const wgIconsPaperclip: {
  name: 'paperclip';
  data: string;
} = {
  name: 'paperclip',
  data: `<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M14.2934 7.36645L8.1667 13.4931C7.41613 14.2437 6.39815 14.6653 5.3367 14.6653C4.27524 14.6653 3.25726 14.2437 2.5067 13.4931C1.75613 12.7425 1.33447 11.7246 1.33447 10.6631C1.33447 9.60166 1.75613 8.58367 2.5067 7.83311L8.22003 2.11978C8.72041 1.61852 9.39941 1.33656 10.1077 1.33594C10.8159 1.33531 11.4954 1.61607 11.9967 2.11645C12.498 2.61682 12.7799 3.29583 12.7805 4.00409C12.7812 4.71235 12.5004 5.39185 12 5.89311L6.27336 11.6064C6.02318 11.8566 5.68385 11.9972 5.33003 11.9972C4.97621 11.9972 4.63688 11.8566 4.3867 11.6064C4.13651 11.3563 3.99596 11.0169 3.99596 10.6631C3.99596 10.3093 4.13651 9.96997 4.3867 9.71978L10.0467 4.06645" stroke="#09090B" stroke-linecap="round" stroke-linejoin="round"/></svg>`
};
export type wgIcon = 'cloud_black' | 'cloud_load' | 'paperclip';
export interface WgIcon {
  name: wgIcon;
  data: string;
}
export type WgIconNameSubset<T extends Readonly<WgIcon[]>> = T[number]['name'];
export const completeIconSet = [
  wgIconsCloudBlack,
  wgIconsCloudLoad,
  wgIconsPaperclip
];
